### ISSUE TITLE
Additional whitespace in first line of answers

### ISSUE THREAD

**Issue by mkrnr** [JoshuaGrams/steno-jig#25]
First of all: Thank you so much for creating this project! I'm still at a very early stage but steno-jig makes the whole experience so much more fun :slightly_smiling_face: 

I also really enjoy the new display but had the problem that the first answer line would not align correctly which sometimes causes an answer word to slip into the next row. That's because plover outputs a whitespace in front of the first word which is currently also displayed. I added a pull request. You can try out the result here: https://mkrnr.com/steno-jig/learn-plover.html?drill=One+Syllable+Words&hints=yes&timeLimit=10&type=shuffled

**Comment by mkrnr** [comment]
Ok, as usual with changes to the css, there are some funny side effects: When having just one row of words, there's a scroll bar for the lesson. I fixed it with adding "overflow:hidden;" to #lesson in style.css but I don't know if that's the solution you want so I won't add this to the pull request...

**Comment by JoshuaGrams** [comment]
That's absolutely deliberate: if you have Plover output a space at the start, steno-jig will display it.  It's something that you need to learn to manage for real typing, so you should start learning right away. The old display didn't do that, and that turned out to be a mistake.

I do need to fix the wrapping: I think the answer should be `white-space: pre` instead of `pre-wrap` but there's some weird bug or css thing where it displays a scroll-bar even though it absolutely shouldn't.  And I got fed up with fighting with it.  I'll have to pick it up again and see if I can finish it off.

**Comment by mkrnr** [comment]
Thank you for the reply! That absolutely makes sense, especially when practicing the Gutenberg sentences.
