### ISSUE TITLE
Allow whitespace in exercise strings (phrasing)

### ISSUE THREAD

**Issue by pete-debiase** [JoshuaGrams/steno-jig#35]
Hi @JoshuaGrams,

I've been having a blast recently drilling steno exercises with Steno Jig. Thank you so much for creating this awesome tool!

Is there any way to remove the answer matching restriction that exercise strings must be single words with no leading or trailing whitespace (i.e., to allow drilling a word set such as the following)?

```JavaScript

TypeJig.WordSets['Phrasing'] = [
    "in the", "of the", "I am not",
];
```

Stenographers often utilize briefing and phrasing techniques to input such phrases in a single stroke. It would be amazing to be able to drill such phrases in random order using the randomization features already supported in Steno Jig.

I spent some time looking through the code this evening and determined that the answer matching code begins around line 73 of the `type-jig.js` file, and I've tried a couple of different approaches so far. One was changing the `answerString.split(/\s+/)` call on line 75 to `answerString.split('_')`. This actually yielded something close to the desired behavior except that it was necessary to input an underscore between every exercise string.

Another approach was extending the `if` statement condition on line 91 to support phrasing as part of the valid prefix determination case. I also tried adding a new `else if` case such as the following (although this turned out to be a sub-optimal approach because even if it had worked, it would only have allowed phrases of two words in length):

```JavaScript

else if((ans + ' ' + answer[i+1]) == ex) {
    // Try to add support for phrasing
    if(hasClass(out, 'incorrect')) this.removeError(ex);
    out.className = 'correct';
}
```

I wasn't able to get the answer matching to work correctly again in either of these cases, and I also ran into issues with getting Steno Jig to recognize that the lesson was complete.

Do you have any thoughts or hints as to how to go about implementing phrasing support?

Kindest regards,

Pete

**Comment by JoshuaGrams** [comment]
Yeah...I was thinking about trying to do that but it seemed like it would be more work than I felt like spending on it.  Steno Jig is a weekend hack that got out of hand, so it's not very carefully structured.

The problem is that currently it splits your given answer into words, *then* asks for that number of words from the exercise.  If some of your exercise units are phrases instead of words, then you would need to restructure the loop.  It would need to loop while the answer string is non-empty, getting a single unit from the exercise and checking to see that it's a prefix of your typed answer.  If it is, mark it correct and continue.  If it isn't, mark some amount of the answer as an error (how much? how do you sync up again?).  So matching arbitrary text turns into essentially writing a full diff algorithm? I think?

If all you need is phrasing, then a better approach would be to modify `TypeJig.Exercise.prototype.nextWord`, at the very bottom of `type-jig.js`.  Instead of returning the value, stick it in a property and then chop words off until it's gone?  Something like this (completely off-the-cuff and untested):

``` Javascript

TypeJig.Exercise.prototype.nextWord = function() {
	if(this.currentUnit.length === 0) {
		var word = rotateAndShuffle(this.words);
		if(word instanceof Array) word = this.select(word);
		this.currentUnit = word.split(/\s+/)
	}
	return this.currentUnit.shift();
}
```

You might need a check in there for the end of the exercise, because `word` will probably be `false` or `undefined` instead of a string?

**Comment by JoshuaGrams** [comment]
Eh.  I added the last bits of code and pushed it.  We'll see how many things that breaks.  It still doesn't solve the problem of giving hints for phrases, but at least it lets you drill them.

**Comment by pete-debiase** [comment]
This works _awesome_ for drilling phrases - thank you so much! I've been playing around with it this evening, and as far as I can tell, everything else still works normally. It's cool that it also still supports inputting the words in a phrase one by one (because you don't always remember to get the whole phrase off in a single stroke).

Regarding hints for phrases, it's possible that by the time steno learners reach the point of starting to drill phrases, they'll be using Steno Jig primarily to build speed rather than to learn steno theory/build steno vocab. And since the hints feature still works normally for the individual words in phrases, it might not be much of an issue at all (just my opinion).

If Steno Jig really did start out as a "weekend hack" as you put it, it's a damned impressive one. None of my weekend steno hacks have ever even graduated off the command line.

Thanks again!
