### ISSUE TITLE
Make stylesheet colour-blind friendly

### ISSUE THREAD

**Issue by SeaLiteral** [JoshuaGrams/steno-jig#36]
I'm not colour blind myself, but I noticed the red-for-wrong green-for-right colour scheme might not be particularly useful for those who can't tell those colours apart. Maybe we could underline the correctly written words or strike-through the ones with mistakes.

**Comment by SeaLiteral** [comment]
Also, on a black and white monitor, there's little contrast between which keys to press and which ones not to press. And if we look for more things that accessibility guidelines discourage, I'm not sure if pixels are the right unit to define font size in. I made a stylesheet that adds underlining and strike-through and darkens the grey and lightens the yellow. I can change the font size unit to em if you want, but I figured that would matter less, since modern browsers have a zoom feature.

**Comment by JoshuaGrams** [comment]
I usually do specify font sizes in other units, but IIRC it needs to be in pixels for the animation stuff to be able to measure/place it properly?  It's probably *possible*, but I seem to remember that it's not a trivial change.

I don't see the need for both underlining and strikethrough.  As long as the highlight is visible it should be enough.  Even without being able to tell the colors apart, you still have highlighted as correct and highlighted and struck-through as incorrect.  The correct marking is mostly unnecessary anyway: it should be the default state (if you're missing more than about 1% of words you're practicing *completely* wrong) and just exists as a minor confirmation that you've moved past that word.

Otherwise the pull request looks good.

**Comment by SeaLiteral** [comment]
I guess we can consider this bug fixed then. And I agree underlining probably isn't very helpful.

As for the font sizes, changing them to 1 em on my own laptop doesn't seem to cause trouble with the animation, but I suppose that may depend on the default font size on the user's computer. And I'm not quite sure what a pixel is. And I seem to remember CSS has its own definition of pixels, which probably means people who can't read small text can make pixels bigger and then we won't really need to use another unit.

**Comment by JoshuaGrams** [comment]
Huh.  Maybe I did find a way around the font size thing.  I've pretty much stopped working on steno-jig, so I don't know if I'll get around to checking into that, but I'll put it on my list.
