### ISSUE TITLE
Graphing Bug

### ISSUE THREAD

**Issue by Chobbes** [JoshuaGrams/steno-jig#53]
It seems like if you start an exercise and then restart it by hitting enter three times the graph contains a flat region of 0 WPM for the amount of time that elapsed prior to restarting the test. It seems weird to me because it looks like the page should reload whenever you reset, but I guess the beginning of the timer isn't being reset somehow?

![2022-06-19T18:35:50-04:00](https://user-images.githubusercontent.com/5215874/174503573-104626d8-4e40-4734-8894-2185b6e85626.png)

**Comment by JoshuaGrams** [comment]
Ah, thanks! That might explain a couple other weirdnesses I've seen with the graph but that didn't seem to actually be throwing any errors. I'll take a look. Sorry for the slow response; we're really getting into summer on the farm now...

**Comment by JoshuaGrams** [comment]
Ah, yeah. The event handler was firing when I cleared the typed text, and then it didn't check properly, so it was recording an empty "change" when you reset. So the time between resetting and when you started running it again. Which I've never noticed because I always wait to reset until I'm ready to go again.

This seems to be fixed for me now, but definitely re-open this if it's not...

**Comment by Chobbes** [comment]
Thanks! It seems to be fixed now :). I figured it might have been a clue to some of the other weird stuff I've seen too, haha.
