### ISSUE TITLE
didactic hints

### ISSUE THREAD

**Issue by laalsaas** [JoshuaGrams/steno-jig#56]
when i use steno jig with the Learn Plover! exercise "one-sylable words", with the hints enabled, it shows **H** as a hint for "had", and **SAEUS** as hint for "says". However, for didactic purposes, briefs should not be shown that early, and the book says that the stroke for "says" is **SEZ**. 

While the hints currently technically are working, i think that for didactic purposes they should work like the book tells you to stroke the word.

**Comment by JoshuaGrams** [comment]
Hmm... it's not as simple as all that, but yeah, maybe. I'll probably do it, but I'll have to think about it a little bit. It's easy enough to customize the hints for that set of lessons, but they're actually for all of Steno Jig, which is a completely separate project from Learn Plover: I just put the exercises from the book in there as a convenience.

> However, for didactic purposes, briefs should not be shown that early

I 100% disagree with this: some of the professional steno teaching things I've seen do introduce briefs right at the very beginning. A bunch of the most common words actually have mandatory briefs (as in, there's no sounded-out way to write them, only a brief). And if you want to talk about things that should not be shown that early: jumping straight from "here are the keys" to "press three of them at once to make a word" is terrible pedagogy IMO.

Anyway. "Had" isn't a mandatory, but I do think it's one that you should learn very early. But yeah, the brief doesn't fit with the spirit of this lesson.

And... I *think* we chose `SAEUS` for the hint because the only way to write "say" is `SAEU`, and then you can modify that chord with all the inflected endings to get the other forms. Which...it's a really common word, you're going to have all its forms memorized anyway, so I bet a lot of people just write `SEZ`. So you could (in general) argue this one either way, though again, the current hint clearly doesn't fit the spirit of this lesson.

And of course Learn Plover also says "Were you able to stroke all those words without looking any of them up?" We originally added the hints as an afterthought and I'm still not sure that they're a good idea pedagogically in the long run, though they sure are convenient.

Which is a ridiculously roundabout way to say that personally I'd probably take "had" and "says" out of this lesson rather than change the hints. But I don't have anything to do with Learn Plover, so I can't change the text. And it explicitly comments on "says", so I probably don't want to take that one out of the lesson on Steno Jig...but I could drop "had" and probably most people wouldn't notice...hmm.

Yeah. I'll probably change the hints for those lessons, but I want to sleep on that. Thanks for pointing it out!
