### ISSUE TITLE
Suggestion: alternative animation scrolling

### ISSUE THREAD

**Issue by panathea** [JoshuaGrams/steno-jig#9]
I've been drilling with steno jig and I'm really enjoying it. I'm using it to learn the LightSpeed.

My biggest issue is that I'm prone to nausea → and the scrolling text moves at such a pace that seems to make me dizzy.

I can think of some solutions:

- Make the animation instant
- Add more natural acceleration so that the animation is still followable, but much quicker
- Introduce a paragraph view like TypeRacer (I can understand that this wouldn't work with really large texts)

I'd be willing to help out, but I wanted to get feedback on your thoughts. My drilling is roughly 75 words per minute right now, in case you wanted to simulate what it looks like.

**Comment by JoshuaGrams** [comment]
Yeah, the scrolling is kind of awful, but I had the crazy idea that I wanted to limit the amount of editing you could do and that was the first thing I got working. I _think_ that what I'd ultimately like is to alternate lines of text with lines of typing as most "real" typing tutors do (e.g. https://youtu.be/DQ3B1PUwr0I?t=2m38s). Possibly with only two lines of text and scroll them _up_ slowly and have them disappear?

Anyway. The main (and only) branch is named `gh-pages` instead of `master` so if you fork it, it will automatically serve the content under your account (i.e. morinted.github.io/steno-jig). There's already (sort of) a flag to scroll instantly: add a second parameter with the value `true` to the `scrollTo` call at line 142 of `type-jig.js`.

https://github.com/JoshuaGrams/steno-jig/blob/gh-pages/type-jig.js#L142

You probably also want to remove the `- 40` at line 270 so they line up properly.

Or you could try fiddling with the ScrollBox's magic numbers (in that same file). If you find better values, let me know. The scrolling code is kind of a mess because I hacked around with it briefly to get the current behaviour when Jason commented on it and never cleaned it up. Also I'm not a fan of pulling in libraries that dwarf my project just to do simple things, so...yeah...it's just plain vanilla javascript. So...if you'd _like_ to work on a better solution, be my guest, but I don't know that I'd wish the current code on most web devs. It's on my list, and I'll move it up toward the top now.

HTH, let me know how it goes, and all that.
